image: node:5.8

stages:
  - test
  - build
  - deploy

# Wait for gitlab-ci-runner 0.9 to have global cache.
cache:
  untracked: true
  paths:
    - node_modules/

before_script:
  - node --version
  - npm --version

test:
  stage: test
  script:
    - npm install --loglevel http
    - npm test
  tags:
    - node

bundle:
  stage: test
  script:
    - npm install --loglevel http
    - npm run build -- -- --release --isomorphic
  tags:
    - node

build:
  stage: build
  script:
    - npm install request-json semver
    - node ./webhooks/build-image.js
  tags:
    - node
  only:
    - /^([0-9]+\.{0,1}){1,3}(\-([a-z0-9]+\.{0,1})+){0,1}(\+(build\.{0,1}){0,1}([a-z0-9]+\.{0,1}){0,}){0,1}$/
    - develop

deploy:
  stage: deploy
  script:
    - npm install request-json semver
    - node ./webhooks/deploy.js
  allow_failure: true
  tags:
    - node
  only:
    - /^([0-9]+\.{0,1}){1,3}(\-([a-z0-9]+\.{0,1})+){0,1}(\+(build\.{0,1}){0,1}([a-z0-9]+\.{0,1}){0,}){0,1}$/
    - develop
