version: '2'
services:
  react-seed:
    container_name: react-seed
    image: portal
    restart: always
    networks:
      - front
    ports:
      - "5000:5000"
    environment:
      SERVER_RENDERING: 1
      REDUX_DEVTOOLS: 0
      FRONTEND_SERVER_PORT: 5000
      NODE_ENV: production
      API_SERVER_HOSTNAME: 'https://abc.com/api'
      API_SERVER_PORT: 80

networks:
  front:
