export const GET_CURRENT_ACTIVITY = {
  value: 'GET_CURRENT_ACTIVITY',
  LOADING: 'GET_CURRENT_ACTIVITY_LOADING',
  SUCCESS: 'GET_CURRENT_ACTIVITY_SUCCESS',
  ERROR: 'GET_CURRENT_ACTIVITY_ERROR',
};

export const GET_LASTWEEK_ACTIVITY = {
  value: 'GET_LASTWEEK_ACTIVITY',
  LOADING: 'GET_LASTWEEK_ACTIVITY_LOADING',
  SUCCESS: 'GET_LASTWEEK_ACTIVITY_SUCCESS',
  ERROR: 'GET_LASTWEEK_ACTIVITY_ERROR',
};
