export const SIGNIN = {
  value: 'SIGNIN',
  LOADING: 'SIGNIN_LOADING',
  SUCCESS: 'SIGNIN_SUCCESS',
  ERROR: 'SIGNIN_ERROR',
};

export const SIGNOUT = {
  value: 'SIGNOUT',
  LOADING: 'SIGNOUT_LOADING',
  SUCCESS: 'SIGNOUT_SUCCESS',
  ERROR: 'SIGNOUT_ERROR',
};

export const GET_CURRENT_SESSION = {
  value: 'GET_CURRENT_SESSION',
  LOADING: 'GET_CURRENT_SESSION_LOADING',
  SUCCESS: 'GET_CURRENT_SESSION_SUCCESS',
  ERROR: 'GET_CURRENT_SESSION_ERROR',
};

export const AWAIT_SIGNIN = {
  value: 'AWAIT_SIGNIN',
  LOADING: 'AWAIT_SIGNIN_LOADING',
  SUCCESS: 'AWAIT_SIGNIN_SUCCESS',
  ERROR: 'AWAIT_SIGNIN_ERROR',
};
