export const GET_CURRENT_USER = {
  value: 'GET_CURRENT_USER',
  LOADING: 'GET_CURRENT_USER_LOADING',
  SUCCESS: 'GET_CURRENT_USER_SUCCESS',
  ERROR: 'GET_CURRENT_USER_ERROR',
};

export const UPDATE_USER = {
  value: 'UPDATE_USER',
  LOADING: 'UPDATE_USER_LOADING',
  SUCCESS: 'UPDATE_USER_SUCCESS',
  ERROR: 'UPDATE_USER_ERROR',
};
